name: Create Release with Changelog

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
          generate_release_notes: true
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install requests
      - name: Extract User Announcement Changes
        run: python .github/extract-user-announcement-changes.py ${{ steps.release.outputs.upload_url }} ${{ github.token }} ${{ github.event.release.tag_name }}
