name: Create User Announcement Release Notes

on:
  workflow_run:
    workflows: [Create Release with Changelog]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: |
          echo '${{ github.event_name }}'
          echo '${{ github.event.workflow_run.event.event_name }}'
          echo '${{ github.event.workflow_run.event.payload.release.body }}'
          echo '${{ github.event.payload.release.upload_url }}'
          echo '${{ github.event.payload.release.body }}'
      - name: Try GitHub Action script
        uses: actions/github-script@v8
        with:
          script: |
            function extractUserAnnouncements(text) {
              if (!text.includes(USER_ANNOUNCEMENT_HEADER)) {
                return;
              }

              const lines = text.split("\n");
              const idx = lines.findIndex((element) => element === `### ${USER_ANNOUNCEMENT_HEADER}`);

              let notes = [];
              for (let line of lines.slice(idx + 1)) {
                if (line.slice(0, 2) === "* ") {
                  const prTitle = line.split(" by")[0];
                  notes.push(prTitle);
                  continue;
                }
                break;
              }

              return notes;
            };

            console.log(context);
            console.log(context.payload.workflow_run.head_branch);
            let release = await github.rest.repos.getReleaseByTag({
              owner: "yousefmoazzam",
              repo: "automatic-release-notes-playground",
              tag: context.payload.workflow_run.head_branch
            });
            console.log(release);
            console.log(release.data.body);

            const lines = extractUserAnnouncements(release.data.body);
            const encoder = new TextEncoder();
            await github.rest.repos.uploadReleaseAsset({
              owner: "yousefmoazzam",
              repo: "automatic-release-notes-playground",
              release_id: release.data.id,
              name: "user-announcements.txt",
              data: encoder.encode(lines.join("\n")),
            });
      - run: pip install requests
      - name: Extract User Announcement Changes
        run: python .github/extract-user-announcement-changes.py ${{ github.event.payload.release.body }} '${{ github.event.payload.release.upload_url }}' '${{ github.token }}'
