name: Create User Announcement Release Notes

on:
  workflow_run:
    workflows: [Create Release with Changelog]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: |
          echo '${{ github.event_name }}'
          echo '${{ context.payload.workflow_run }}'
          echo '${{ context.payload.workflow_run.event }}'
          echo '${{ context.payload.workflow_run.event.event_name }}'
          echo '${{ github.event.workflow_run.event.event_name }}'
          echo '${{ github.event.workflow_run.event.payload.release.body }}'
          echo '${{ github.event.payload.release.upload_url }}'
          echo '${{ github.event.payload.release.body }}'
      - run: pip install requests
      - name: Extract User Announcement Changes
        run: python .github/extract-user-announcement-changes.py ${{ github.event.payload.release.body }} '${{ github.event.payload.release.upload_url }}' '${{ github.token }}'
