name: Create User Announcement Release Notes

on:
  workflow_run:
    workflows: [Create Release with Changelog]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract User Announcement Changes
        uses: actions/github-script@v8
        with:
          script: |
            const REPO_OWNER = "yousefmoazzam";
            const REPO_NAME = "automatic-release-notes-playground";
            const FILENAME = "user-announcements.txt";
            const USER_ANNOUNCEMENT_HEADER = "Notable Changes for Users";
            
            function extractUserAnnouncements(text) {
              if (!text.includes(USER_ANNOUNCEMENT_HEADER)) {
                return [];
              }

              const lines = text.split("\n");
              const idx = lines.findIndex((element) => element === `### ${USER_ANNOUNCEMENT_HEADER}`);

              let notes = [];
              for (let line of lines.slice(idx + 1)) {
                if (line.slice(0, 2) === "* ") {
                  const prTitle = line.split(" by")[0];
                  notes.push(prTitle);
                  continue;
                }
                break;
              }

              return notes;
            };

            let release = await github.rest.repos.getReleaseByTag({
              owner: REPO_OWNER,
              repo: REPO_NAME,
              tag: context.payload.workflow_run.head_branch
            });

            const lines = extractUserAnnouncements(release.data.body);
            const encoder = new TextEncoder();
            await github.rest.repos.uploadReleaseAsset({
              owner: REPO_OWNER,
              repo: REPO_NAME,
              release_id: release.data.id,
              name: FILENAME,
              data: encoder.encode(lines.join("\n")),
            });
